repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: Format code with Black
        args: [--line-length, "128"]

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        name: Format Python code in documentation with Black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Lint Python code with Flake8
        args: [--ignore, "E203,E501,W503"]
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort Python imports with isort
        args: [--profile, "black"]

# - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports]
  #       additional_dependencies: [types-freezegun]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
        name: Validate JSON files
        exclude: '.*\.ipynb$'
      - id: check-toml
        name: Validate TOML files
      # - id: check-yaml
      #   name: Validate YAML files
      - id: debug-statements
        name: Check for and remove debug statements (e.g., print)
      - id: end-of-file-fixer
        name: Ensure files end with a newline
      - id: fix-byte-order-marker
        name: Remove byte order markers (BOM)
      - id: trailing-whitespace
        name: Remove trailing whitespace

  # Pytest: Run tests before committing
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run Pytest to execute all tests
  #       entry: poetry run python test/run.py
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       working_directory: backend
