apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: 'langchain'
deploy:
  cloudrun: {}
profiles:
  - name: 'staging'
    manifests:
      rawYaml:
        - 'app-stg.yaml'
  - name: 'prod'
    manifests:
      rawYaml:
        - 'app-prod.yaml'
